name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt install shc dialog
      
    - name: Build
      run: make
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v2.3.1
      with:
         name: build/power-mgmt
         if-no-files-found: warn
  
    - name: Build debug
      run: make debug
      
    - name: Upload debug artifact
      uses: actions/upload-artifact@v2.3.1
      with:
         name: build/power-mgmt-debug
         if-no-files-found: warn
